# Generated by Django 3.2.16 on 2022-11-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sortno',
        ),
    ]
