# Generated by Django 3.2.16 on 2022-11-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_rename_address_revendeur_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(blank=True, max_length=120, null=True)),
                ('client', models.CharField(blank=True, max_length=120, null=True)),
                ('montant_payement', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cree_par_finance', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_finance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
